name: Test the File Dup action
on:
  push:
    paths:
      - ".github/workflows/test-action__file-dup-action.yml"
      - ".github/workflows/test-action__setup-gh-cli.yml"
      - "actions/setup-gh-cli/**"
      - "actions/file-dup-action/**"
jobs:
  sanity-check-file-dup-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        working-directory: ./actions/file-dup-action
        run: npm install && npm run build
      - name: install dependencies
        working-directory: ./actions/setup-gh-cli
        run: npm install && npm run build
      - uses: ./actions/setup-gh-cli
        with:
          token: ${{ secrets.TIANHAOZ_GITHUB_TOKEN }}
      - uses: ./actions/file-dup-action
        with:
          username: "tianhaoz95"
          email: "tianhaoz@umich.edu"
          token: ${{ secrets.TIANHAOZ_GITHUB_TOKEN }}
          config_files: "actions/file-dup-action/example_config.json"
          method: "dry_run"
          branch: "chore/dup-files"
